#空闲连接保活
#解决druid 日志报错：discard long time none received connection:xxx

log-pattern: "%d{yy-MM-dd' 'HH:mm:ss.SSS} [%-5level] [%15.15t] [%40.40c{39}:%4.4L] - %m%n"

logging:
  pattern:
    console: ${log-pattern}
    file: ${log-pattern}
  file:
    path: ./logs

druid:
  mysql:
    usePingMethod: false

server:
  servlet:
    session:
      cookie:
        name: SECURITY-TOKEN
  #开启响应压缩
  compression:
    enabled: true
    #压缩类型
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    #使用压缩的体积阈值
    min-response-size: 1024

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      # 上传单个文件的体积限制
      max-file-size: 1024MB
      # 单次请求上传的最大限制
      max-request-size: 1024MB
  #      active: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 2
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 60000
      max-evictable-idle-time-millis: 500000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
  # JPA配置
  jpa:
    database: mysql
    # 在控制台打印SQL
    show-sql: true
    # 数据库平台
    database-platform: mysql
    hibernate:
      # 每次启动项目时，数据库初始化策略
      ddl-auto: update
    properties:
      hibernate:
        # 指定默认的存储引擎为InnoDB
        dialect: org.hibernate.dialect.MySQLDialect

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml


system:
  log:
    #日志保留天数, 超过时间的将被存入旧日志表
    days: 1
    #旧日志表保留天数, 超过时间的将被删除
    days-old: 180
  database:
    #自动备份开关
    auto-backup: true
    #保留的最大镜像数量, 每天凌晨清理,保留最新的。0或负数表示不限制
    max-backup: 10
    # mysql client 安装包地址(避免修改)
    mysql-client:
      - https://downloads.mysql.com/archives/get/p/23/file/mysql-community-client-8.0.30-1.el8.x86_64.rpm
      - https://downloads.mysql.com/archives/get/p/23/file/mysql-community-client-plugins-8.0.30-1.el8.x86_64.rpm
      - https://downloads.mysql.com/archives/get/p/23/file/mysql-community-common-8.0.30-1.el8.x86_64.rpm
      - https://downloads.mysql.com/archives/get/p/23/file/mysql-community-libs-8.0.30-1.el8.x86_64.rpm
