logging:
  level:
    com.gin: info

spring:
  datasource:
    url: jdbc:mysql://192.168.0.180:3306/spring-boot-3-template?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: lzbx2837200
  data:
    redis:
      host: 192.168.0.68
      password: lzbx2837200
      database: 8
