logging:
  level:
    com.gin: info

# 接口文档开关 (生产环境建议关闭)
knife4j:
  enable: true

spring:
  datasource:
    url: jdbc:mysql://192.168.0.180:3306/spring-boot-3-template?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: lzbx2837200
  data:
    redis:
      host: 192.168.0.68
      password: lzbx2837200
      database: 8

system:
  #注册功能开放 关闭后只能由管理员创建新用户
  new-user: true
  #文件根目录,本系统管理的文件将全部放在该目录下
  home-path: /home/springboot3